version: '3.8'
services:
    db:
        image: mysql:8
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - '3308:3306'
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
            MYSQL_USER: root
            MYSQL_PASSWORD: password
        volumes:
            - mysql_db:/var/lib/mysql
            - mysql_config:/etc/mysql/conf.d
    api:
        build: .
        command: yarn start
        ports:
            - 4001:4000
        depends_on:
            - db
        links:
            - db
        volumes:
            - /app/node_modules
            - .:/app
        environment:
            - PORT=4000
            - DB_HOST=db
            - DB_NAME=apiRestDb
            - DB_USER=root
            - DB_PASSWORD=password
volumes:
    mysql_db:
    mysql_config:
